version: '3.8'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: veterinary
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 12345
      DB_DATABASE: veterinary
      SECRET_TOKEN: BYtUf9lgt+qw4PVnsC0R1g==
volumes:
  mysql-data: